server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /var/www/portfolio_jorge;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|svg|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
